repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: validate-ssot
        name: Validate SSOT
        entry: python ai_paralegal_ssot/validate_ssot.py
        language: system
        files: \.(csv|json)$
        pass_filenames: false
      - id: check-proof-tokens
        name: Check Proof Tokens
        entry: python kg/validate_proof_tokens.py
        language: system
        files: edges_final\.csv$
        pass_filenames: false
      - id: test-api
        name: Run API Tests
        entry: python -m pytest tests/test_api.py -v
        language: system
        files: ^(api/|tests/)
        pass_filenames: false
      - id: test-kg
        name: Run KG Tests
        entry: python -m pytest tests/test_kg_studio.py tests/test_advanced_extraction.py -v
        language: system
        files: ^(kg/|tests/)
        pass_filenames: false
      - id: test-auth
        name: Run Auth Tests
        entry: python -m pytest tests/test_auth.py -v
        language: system
        files: ^(api/service/auth\.py|tests/)
        pass_filenames: false
      - id: test-jobs
        name: Run Job Tests
        entry: python -m pytest tests/test_jobs.py -v
        language: system
        files: ^(api/service/jobs\.py|tests/)
        pass_filenames: false
